name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: |
          npm run build
          node dist/cjs/index.cjs
          node dist/esm/index.mjs
      - run: npm run eslint
      - run: npm run prettier:check
      - run: npm test
        env:
          CI: true

  html-validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        html-validate: [8, 9, 10, 11]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Use Node.js 18
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22.x
      - name: Build
        run: |
          npm ci
          if [[ ${{ matrix.html-validate }} -lt 10 ]]; then
            npm install jest@29 jest-environment-jsdom@29 jest-snapshot@29 jest-diff@29 jest-runtime@29 @types/jest@29
          fi
          npm run build
          find dist
      - name: package.json lint
        run: |
          npm pack
          npm exec npm-pkg-lint -- --allow-dependency @sidvind/build-scripts
      - name: Install html-validate v${{ matrix.html-validate }}
        run: |
          npm install $(npx -y npm-min-peer html-validate --major ${{ matrix.html-validate }} --with-name)
          npm ls html-validate
      - name: Integration test
        run: |
          for spec in test/*.spec.ts; do sed 's#../src/transform#../dist/cjs/index.cjs#g' -i "${spec}"; done
          sed '/dist/s#jest.mock#//#' -i "test/htmlvalidate.spec.ts"
          npm test -- --no-coverage test
        env:
          CI: true
